version: '3'
services:
    web:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "8005:80"
      depends_on:
         - db
    db:
      image: mysql:latest
      environment:
         MYSQL_ROOT_PASSWORD: password
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
         - db
      environment:
         PMA_HOST: db
         PMA_PORT: 3306
         PMA_ARBRITRARY: 1
      ports:
         - "8006:80"
